apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        images: kozyaura/node-app:0f7c7f61eba7bfaeac92e6ac4f2de62cb4339eb1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
